const passport = require('passport')
const session = require('express-session')
const flash = require('connect-flash')
const SQLiteStore = require('connect-sqlite3')(session)
const { secret } = require('../../configs/env')